Add XOR function to calculator
kairproject/practice_collaboration pull request #28
Opened 2019-01-12 05:25 UTC by penpaperkeycode

Add xor calculate function code

2019-01-12 16:12 UTC, IntelligenceDatum commented
Please review my request :)

2019-01-14 05:04 UTC, seungjaeryanlee submitted a review, later dismissed
`.idea/` folder should not be included in the PR.

2019-01-14 06:37 UTC, Curt-Park commented
Please fix the PR name.

2019-01-15 02:16 UTC, IntelligenceDatum commented
> `.idea/` folder should not be included in the PR.

Thanks for notice! I deleted it

2019-01-15 02:16 UTC, IntelligenceDatum commented
> Please fix the PR name.

Yes master, I changed PR title.

2019-01-15 02:18 UTC, Curt-Park commented
Please check the code. You just pushed the conflicting lines.

2019-01-15 04:13 UTC, IntelligenceDatum commented
> Please check the code. You just pushed the conflicting lines.

Master, I've update the code agian. plz check my humble code.

2019-01-15 04:21 UTC, Curt-Park commented on test_calculator.py
> +        """Put your test cases for sub that starts with assert."""
Please add a description for the test cases.

2019-01-15 05:02 UTC, IntelligenceDatum commented on test_calculator.py
> +        """Put your test cases for sub that starts with assert."""
Add Done! 

How can i solve the ryans query above?

2019-01-15 09:41 UTC, Curt-Park approved these changes
Good job. Looks good to me.

2019-01-16 01:29 UTC, penpaperkeycode commented
> `.idea/` folder should not be included in the PR.

Please review my code again.

2019-01-16 01:43 UTC, seungjaeryanlee requested changes
Please fix the typo in the PR title: the ^ operator is the XOR operator, not the XNOR operator. Otherwise, the PR looks good!

2019-01-16 02:19 UTC, Curt-Park commented
@seungjaeryanlee I missed that point! Great review!

2019-01-16 02:25 UTC, penpaperkeycode commented
> Please fix the typo in the PR title: the ^ operator is the XOR operator, not the XNOR operator. Otherwise, the PR looks good!

My bad! Thank you :)

2019-01-16 02:56 UTC, seungjaeryanlee approved these changes
Looks good! :+1:

2019-01-16 04:02 UTC, merged